"""

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.

"""

def fib(current, max_n):

	if current[-1] > max_n:

		return current[:-1]

	else:

		current.append(current[-1] + current[-2])

		return fib(current, max_n)


if __name__ == '__main__':

	total = 0

	for i in fib([1,2], 4e6):

		if i % 2 == 0:

			total += i

	print total
